CREATE TABLE IF NOT EXISTS projects (
    project_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_name TEXT NOT NULL,
    project_type TEXT NOT NULL,
    project_summary TEXT NOT NULL,
    active INTEGER DEFAULT 1,
    user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE NOT NULL
);